FROM golang AS go
RUN go get github.com/fc00/cjdcmd-ng
RUN ls
FROM docker.io/debian:stable-slim
RUN apt-get update
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y inn2 || true
RUN sed -i -re 's/#?(domain:)\s*.*$/\1 localhost/' /etc/news/inn.conf
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y daemontools curl
RUN cd /root && curl -Os https://mildred.github.io/0feed-cjdns/cjdns-linux-x86_64-20.tar.bz2
RUN cd /bin && tar --strip-components=1 -xvf /root/cjdns-linux-x86_64-20.tar.bz2 cjdns-linux-x86_64-20/cjdroute
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y iproute2 vim-tiny
COPY service /service
VOLUME ["/var/log/cjdns", "/etc/cjdns"]
CMD ["svscan", "/service"]

