#!/bin/sh

mkdir -p /etc/cjdns
if ! [ -e /etc/cjdns/cjdroute.conf ]; then
  (set -x; cjdroute --genconf >/etc/cjdns/cjdroute.conf)
fi
sed -i -re 's|// "logTo":"stdout"|"logTo":"stdout"|' /etc/cjdns/cjdroute.conf
sed -i -re 's|// "noBackground":0|"noBackground":1|' /etc/cjdns/cjdroute.conf
mkdir -p /dev/net
if [ ! -c /dev/net/tun ]; then
    mknod /dev/net/tun c 10 200
fi
exec 2>&1
set -x
exec cjdroute --nobg </etc/cjdns/cjdroute.conf
