#!/bin/sh

cp readers.conf /etc/news/readers.conf
cp incoming.conf /etc/news/incoming.conf
cp innfeed.conf /etc/news/infeed.conf
cp control.ctl.local /etc/news/control.ctl.local
sed -r -i \
  -e 's/^pgpverify:.*/pgpverify: false/' \
  -e 's/^organization:.*/organization: "Hyperboria News"/' \
  -e 's/^nnrpdflags:.*/nnrpdflags: "-n"/' \
  /etc/news/inn.conf
sed -r -i \
  -e 's/^\*:A.*/*:A:never:never:never/' \
  /etc/news/expire.ctl

if [ ! -d /run/news ]; then
  mkdir -p /run/news
  chown news:news /run/news
  chmod 775 /run/news
fi

clean_exit(){
  /etc/init.d/inn2 stop
  exit 0
}

trap clean_exit 0 2 15

/etc/init.d/inn2 start

sleep 1m

while /etc/init.d/inn2 status >/dev/null 2>&1; do
  sleep 1m
done

/etc/init.d/inn2 status
